# Generated by Django 2.2.19 on 2021-03-18 03:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='redirect',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
