# Generated by Django 2.2.19 on 2021-03-18 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0002_auto_20210318_0328'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='redirect',
            managers=[
            ],
        ),
    ]
